//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutingServerService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IProxyService")]
    public interface IProxyService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/getStation", ReplyAction="http://tempuri.org/IProxyService/getStationResponse")]
        string getStation(int number, string chosenContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/getStation", ReplyAction="http://tempuri.org/IProxyService/getStationResponse")]
        System.Threading.Tasks.Task<string> getStationAsync(int number, string chosenContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/getContracts", ReplyAction="http://tempuri.org/IProxyService/getContractsResponse")]
        string getContracts();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/getContracts", ReplyAction="http://tempuri.org/IProxyService/getContractsResponse")]
        System.Threading.Tasks.Task<string> getContractsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/getAllStationsOfAContract", ReplyAction="http://tempuri.org/IProxyService/getAllStationsOfAContractResponse")]
        string getAllStationsOfAContract(string chosenContract);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProxyService/getAllStationsOfAContract", ReplyAction="http://tempuri.org/IProxyService/getAllStationsOfAContractResponse")]
        System.Threading.Tasks.Task<string> getAllStationsOfAContractAsync(string chosenContract);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProxyServiceChannel : RoutingServerService.ServiceReference1.IProxyService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyServiceClient : System.ServiceModel.ClientBase<RoutingServerService.ServiceReference1.IProxyService>, RoutingServerService.ServiceReference1.IProxyService {
        
        public ProxyServiceClient() {
        }
        
        public ProxyServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getStation(int number, string chosenContract) {
            return base.Channel.getStation(number, chosenContract);
        }
        
        public System.Threading.Tasks.Task<string> getStationAsync(int number, string chosenContract) {
            return base.Channel.getStationAsync(number, chosenContract);
        }
        
        public string getContracts() {
            return base.Channel.getContracts();
        }
        
        public System.Threading.Tasks.Task<string> getContractsAsync() {
            return base.Channel.getContractsAsync();
        }
        
        public string getAllStationsOfAContract(string chosenContract) {
            return base.Channel.getAllStationsOfAContract(chosenContract);
        }
        
        public System.Threading.Tasks.Task<string> getAllStationsOfAContractAsync(string chosenContract) {
            return base.Channel.getAllStationsOfAContractAsync(chosenContract);
        }
    }
}
